#!/bin/bash

source env.sh
docker run --rm -it \
-e POSTGRES_USER=$POSTGRES_USER \
-e POSTGRES_HOST=$DB_CONTAINER \
-e POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
-v /Volumes/DevHD/bloggymcblogface/src:/src \
-p 8000:8000 \
--net=$NETWORK \
--name=$DJANGO_CONTAINER \
django sh -c "cd /src/bloggy; python manage.py $*"
